### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by dan-f**
@jzoldak

### CODE REVIEW

**Comment by benmadrone** [comment]
beat me to it, @dan-f ! :+1:

**Comment by benmadrone** [comment]
Och actually @dan-f should the Makefile accommodate creating a virtualenv?

**Comment by jzoldak** [comment]
Awesome. @benmadrone yeah, let's pick that up on a subsequent PR. I just added you to the Trello board that @dan-f set up.

**Comment by dan-f** [comment]
Sorry I was on the bus and wasn't really able to respond :stuck_out_tongue:. I'd actually like to not implement a make target for installing/creating a virtualenv. It's a global utility and the install requires messing with your path, so it feels out of scope for this project. The install is really well documented and I'd be happy to document that in the README.

**Comment by jzoldak** [comment]
OK @dan-f that make sense to me.

**Pull request merged**
